package(default_visibility = ["//visibility:public"])

cc_library(
	name = "statemachine",
	srcs = glob(["statemachine/**/*.cpp"]),
	includes = ["statemachine"],
	hdrs = glob(["statemachine/**/*.h"]),
)

cc_library(
  name = "logging",
  srcs = glob(["logging/**/*.cpp"]),
  hdrs = glob(["logging/**/*.h"]),
  includes = ["logging"]
)
